# Generated by Django 5.0 on 2024-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truckpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_email', models.EmailField(max_length=30, unique=True)),
                ('t_password', models.CharField(max_length=20)),
                ('t_contact', models.CharField(max_length=11, unique=True)),
                ('t_rcnumber', models.CharField(max_length=50, unique=True)),
                ('t_aadharcard_details', models.CharField(max_length=30, unique=True)),
                ('t_pancard_details', models.CharField(max_length=30, unique=True)),
                ('t_drivinglicence_details', models.CharField(max_length=30, unique=True)),
                ('t_picture', models.ImageField(default='pic-1.jpg', upload_to='images/')),
            ],
        ),
    ]
