# Generated by Django 5.0 on 2024-03-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckpartner',
            name='t_picture',
            field=models.ImageField(default='images/pic-1.jpg', upload_to='images/'),
        ),
    ]
