# Generated by Django 5.0 on 2024-03-13 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_booking_active_booking_cancel_active_and_more'),
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckpartner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
