# Generated by Django 5.0 on 2024-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
