# Generated by Django 5.0 on 2024-03-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_alter_package_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner'),
        ),
    ]
