# Generated by Django 5.0 on 2024-03-14 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_alter_package_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='truck',
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='package_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='truck_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
