# Generated by Django 5.0 on 2024-03-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_booking_active_booking_cancel_active_and_more'),
        ('myapp2', '0007_delete_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
    ]
