# Generated by Django 5.0 on 2024-03-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_truckpartner_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
