# Generated by Django 5.0 on 2024-03-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0009_truckpartner_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckpartner',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='truckpartner',
            name='user',
        ),
    ]
