# Generated by Django 5.0 on 2024-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_remove_truckpartner_booking_remove_truckpartner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='on_work',
            field=models.BooleanField(default=False),
        ),
    ]
