# Generated by Django 5.0 on 2024-03-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0011_truckpartner_on_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='statuscheck',
            field=models.BooleanField(default=False),
        ),
    ]
