# Generated by Django 5.0 on 2024-03-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0012_truckpartner_statuscheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckpartner',
            name='statuscheck',
        ),
    ]
