# Generated by Django 5.0 on 2024-03-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_statuscheck'),
        ('myapp2', '0013_remove_truckpartner_statuscheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trip', models.PositiveIntegerField()),
                ('today_earning', models.PositiveBigIntegerField()),
                ('total_earning', models.PositiveBigIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
                ('truckpartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
