# Generated by Django 5.0 on 2024-03-19 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_statuscheck'),
        ('myapp2', '0014_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rides',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='today_earning',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='total_earning',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='total_trip',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='truckpartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
