# Generated by Django 5.0 on 2024-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0015_rides_end_date_rides_start_date_alter_rides_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='today_earning',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rides',
            name='total_earning',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rides',
            name='total_trip',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
