# Generated by Django 5.0 on 2024-03-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0016_alter_rides_today_earning_alter_rides_total_earning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='user',
        ),
    ]
