# Generated by Django 5.0 on 2024-03-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0017_remove_rides_booking_remove_rides_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='end_date',
        ),
    ]
