# Generated by Django 5.0 on 2024-03-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0018_remove_rides_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='start_date',
            new_name='timestamp',
        ),
    ]
