# Generated by Django 5.0 on 2024-03-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0019_rename_start_date_rides_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='timestamp',
            new_name='start_time',
        ),
    ]
