# Generated by Django 5.0 on 2024-03-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0020_rename_timestamp_rides_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
