# Generated by Django 5.0 on 2024-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0021_alter_rides_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='today_earning',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='total_earning',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='total_trip',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
