# Generated by Django 5.0 on 2024-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0022_alter_rides_start_time_alter_rides_today_earning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='expiry_time',
            field=models.DateTimeField(null=True),
        ),
    ]
