# Generated by Django 5.0 on 2024-03-21 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0023_rides_expiry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('rides', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.rides')),
                ('truckpartner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner')),
            ],
        ),
    ]
