# Generated by Django 5.0 on 2024-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0024_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_holder_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='account_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='ifsc_code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
