# Generated by Django 5.0 on 2024-03-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('housetype', models.CharField(max_length=30)),
                ('Booking_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_email', models.EmailField(max_length=30, unique=True)),
                ('u_password', models.CharField(max_length=20)),
                ('u_contact', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Truckpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_email', models.EmailField(max_length=30, unique=True)),
                ('t_password', models.CharField(max_length=20)),
                ('t_contact', models.CharField(max_length=11)),
                ('t_address', models.CharField(max_length=50)),
                ('t_aadharcard_details', models.CharField(max_length=30, unique=True)),
                ('t_pancard_details', models.CharField(max_length=30, unique=True)),
                ('t_drivinglicence_details', models.CharField(max_length=30, unique=True)),
                ('t_bank_details', models.CharField(max_length=30, unique=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
