# Generated by Django 5.0 on 2024-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='finish_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='house_type_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='on_the_way_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status_active',
            field=models.BooleanField(default=False),
        ),
    ]
