# Generated by Django 5.0 on 2024-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_booking_active_booking_cancel_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='statuscheck',
            field=models.BooleanField(default=False),
        ),
    ]
