# Generated by Django 5.0.4 on 2024-04-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Tcontact',
        ),
    ]
